/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

SELECT * FROM gold.dim_customers
SELECT * FROM gold.dim_products
SELECT * FROM gold.fact_sales

-- Find total customers by countries
SELECT country, COUNT(customer_key) as total_csutomer
FROM gold.dim_customers
GROUP BY country 
ORDER BY total_csutomer DESC

-- Find total customers by gender
SELECT gender, COUNT(customer_key) as total_csutomer
FROM gold.dim_customers
GROUP BY gender 
ORDER BY total_csutomer DESC

-- Find total products by category
SELECT category, COUNT(product_key) as total_product
FROM gold.dim_products
GROUP BY category 
ORDER BY total_product DESC

-- What is the average costs in each category?
SELECT category, AVG(cost) as avg_cost
FROM gold.dim_products
GROUP BY category 
ORDER BY avg_cost DESC

-- What is the total revenue generated for each category?
SELECT p.category, SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY category
ORDER BY total_revenue DESC

-- What is the total revenue generated by each customer?
SELECT c.customer_key, c.first_name, c.last_name, SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
SELECT c.country, SUM(s.quantity) AS items_sold
FROM gold.fact_sales s 
LEFT JOIN gold.dim_customers c 
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY items_sold DESC

